/* ─── Shared styles for the papers/ reanalysis pages ─── */
const MONO = "'JetBrains Mono', 'Fira Code', 'SF Mono', monospace";
const SERIF = "'Instrument Serif', Georgia, 'Times New Roman', serif";
const SANS = "'DM Sans', 'Helvetica Neue', Arial, sans-serif";

export const FONTS = { MONO, SERIF, SANS };

/* ─── Color palette (dark, matches site) ─── */
export const C = {
  bg:        '#08080f',
  bgDeep:    '#03030a',
  bgCard:    '#0c0c18',
  bgPanel:   '#0d1117',
  text:      '#e2e8f0',
  textMuted: '#94a3b8',
  textDim:   '#64748b',
  border:    '#1a1a2e',
  borderLt:  '#1e293b',
  blue:      '#3b82f6',
  blueGlow:  '#58a6ff',
  green:     '#22c55e',
  greenDim:  '#10b981',
  red:       '#ef4444',
  yellow:    '#d29922',
  amber:     '#f59e0b',
  purple:    '#a78bfa',
  cyan:      '#22d3ee',
  nature:    '#0072b1',
};

/* ─── Reusable inline-style factories ─── */
export const paperStyles = {
  page: {
    background: C.bg,
    color: C.text,
    fontFamily: SANS,
    fontSize: 16,
    lineHeight: 1.7,
    minHeight: '100vh',
  },
  header: {
    background: `linear-gradient(135deg, ${C.bgDeep} 0%, #0a0f1a 100%)`,
    borderBottom: `1px solid ${C.border}`,
    padding: '3rem 0 2.5rem',
  },
  headerInner: (mob) => ({
    maxWidth: 1100,
    margin: '0 auto',
    padding: mob ? '0 16px' : '0 2rem',
  }),
  sectionNav: {
    position: 'sticky',
    top: 38,
    zIndex: 50,
    background: C.bgDeep + 'ee',
    backdropFilter: 'blur(12px)',
    borderBottom: `1px solid ${C.border}`,
    padding: '0.5rem 0',
  },
  navInner: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: '0 1rem',
    display: 'flex',
    gap: 4,
    overflowX: 'auto',
    WebkitOverflowScrolling: 'touch',
    msOverflowStyle: 'none',
    scrollbarWidth: 'none',
  },
  navLink: (active) => ({
    fontFamily: MONO,
    fontSize: 11,
    fontWeight: active ? 700 : 400,
    color: active ? C.cyan : C.textDim,
    textDecoration: 'none',
    padding: '6px 10px',
    borderRadius: 4,
    whiteSpace: 'nowrap',
    background: active ? C.cyan + '15' : 'transparent',
    border: 'none',
    cursor: 'pointer',
    transition: 'color 0.2s',
  }),
  content: (mob) => ({
    maxWidth: 1100,
    margin: '0 auto',
    padding: mob ? '0 16px 4rem' : '0 2rem 4rem',
  }),
  section: {
    padding: '3rem 0',
    borderBottom: `1px solid ${C.border}`,
  },
  sectionNum: {
    fontFamily: MONO,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: C.cyan,
    marginBottom: 8,
  },
  h2: {
    fontFamily: SERIF,
    fontSize: '1.6rem',
    fontWeight: 400,
    fontStyle: 'italic',
    lineHeight: 1.3,
    marginBottom: '1rem',
    color: C.text,
  },
  h3: {
    fontFamily: SANS,
    fontSize: '1.05rem',
    fontWeight: 600,
    margin: '1.5rem 0 0.75rem',
    color: C.text,
  },
  p: {
    marginBottom: '1rem',
    maxWidth: 680,
    color: C.textMuted,
  },
  dual: (mob) => ({
    display: 'grid',
    gridTemplateColumns: mob ? '1fr' : '1fr 1fr',
    gap: '1.5rem',
    margin: '1.5rem 0',
  }),
  panelTheirs: {
    background: C.bgCard,
    border: `1px solid ${C.border}`,
    borderRadius: 8,
    padding: '1.5rem',
    minWidth: 0,
    overflow: 'hidden',
  },
  panelGeo: {
    background: C.bgPanel,
    border: `1px solid ${C.borderLt}`,
    borderRadius: 8,
    padding: '1.5rem',
    minWidth: 0,
    overflow: 'hidden',
  },
  panelLabel: (color) => ({
    fontFamily: MONO,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 12,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    color,
  }),
  dot: (color) => ({
    width: 6, height: 6, borderRadius: '50%', background: color, display: 'inline-block',
  }),
  eq: {
    background: C.blueGlow + '0a',
    borderLeft: `3px solid ${C.blueGlow}`,
    padding: '1rem 1.2rem',
    margin: '1rem 0',
    borderRadius: '0 6px 6px 0',
    fontFamily: MONO,
    fontSize: 14,
    lineHeight: 1.9,
    color: C.text,
  },
  quote: {
    borderLeft: `3px solid ${C.amber}`,
    padding: '0.75rem 1.2rem',
    margin: '1rem 0',
    fontStyle: 'italic',
    color: C.textMuted,
    background: C.amber + '08',
    borderRadius: '0 6px 6px 0',
    fontSize: 15,
  },
  quoteSource: {
    fontStyle: 'normal',
    fontSize: 12,
    fontFamily: MONO,
    marginTop: 6,
    color: C.amber,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 14,
    margin: '0.75rem 0',
  },
  th: (color = C.cyan) => ({
    fontFamily: MONO,
    fontWeight: 600,
    fontSize: 11,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    textAlign: 'left',
    padding: '0.5rem 0.6rem',
    borderBottom: `2px solid ${color}`,
    color,
  }),
  td: {
    padding: '0.45rem 0.6rem',
    borderBottom: `1px solid ${C.border}`,
    fontFamily: MONO,
    fontSize: 13,
    color: C.textMuted,
  },
  good:  { color: C.green, fontWeight: 600 },
  bad:   { color: C.red, fontWeight: 600 },
  warn:  { color: C.yellow, fontWeight: 600 },
  verdict: (type) => {
    const m = { match: C.green, predict: C.blueGlow, inversion: C.yellow };
    const c = m[type] || C.green;
    return {
      display: 'inline-block', fontFamily: MONO, fontSize: 11, fontWeight: 700,
      letterSpacing: 1, textTransform: 'uppercase', padding: '4px 10px',
      borderRadius: 3, margin: '4px 0', background: c + '18', color: c,
      border: `1px solid ${c}44`,
    };
  },
  insight: {
    background: `linear-gradient(135deg, ${C.amber}08, ${C.amber}03)`,
    border: `1px solid ${C.amber}25`,
    borderRadius: 8,
    padding: '1.25rem 1.5rem',
    margin: '1.5rem 0',
  },
  insightTitle: {
    fontFamily: MONO,
    fontWeight: 700,
    fontSize: 11,
    color: C.amber,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
};
